branches:
  only:
<<<<<<< HEAD
  - assignment3
=======
  - master
>>>>>>> 8c3dfb10945283bedc48075ac1d4a2765a761ed2

language: java
jdk:
  - oraclejdk8
<<<<<<< HEAD
services:
  - mysql
  
##test:
  ##adapter: mysql2
  #database: user_database
  #username: travis
  #encoding: utf8
  
#before_install:
 # - mysql -e 'CREATE DATABASE IF NOT EXISTS user_database;'
=======

>>>>>>> 8c3dfb10945283bedc48075ac1d4a2765a761ed2
env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew war
<<<<<<< HEAD
  - ./gradlew test --info 
  
=======
  - ./gradlew test --info

>>>>>>> 8c3dfb10945283bedc48075ac1d4a2765a761ed2
notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu
