branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build

after_success:
  - mkdir codedeploy
  - ls -al
  - mv appspec.yml  codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd
  - gem update --system
  
deploy:
- provider: s3
  access_key_id: $access_key_id
  secret_access_key: $access_key
  bucket: storageforgithubdeploy
  region: ap-northeast-2
  skip_cleanup: true

