branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build

after_success:
  - mkdir codedeploy
  - zip -r WebApp1.zip build/libs/ROOT.war appspec.yml restartTomcat.sh infrastructure/aws/cloudwatch/awslogs.conf startCloudWatch.sh
  - ls -al
  - mv WebApp1.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd

deploy:
- provider: s3
  access_key_id: AKIAJJURQ7HUKCJBHXIA
  secret_access_key:
    secure: "pXk6T4/9Kf8GKZbx/umbgsUrY9ds+MQLo3xCbnVlxukO2DL5J7qWfX7LRndn6HkzWpSFJdo/TfAF+mAAW9jBRom4Bx7dvue9gaeNfxmy7ESpBzPIq9UTfExUFPkD8be3s7NwXTVXThxdWNFcn+ITS8lRQLIlmvpLXthbJ0jjAYE9Saw0MGK8EjcN2SXHa4K5a/YsUER5lRBkaCDM4aOkzCvl1e4gDmY55RkjidzgXkGM/8qAda9rVHD5Xs+OcBng/3UCaYW+LGI8WYw9XJvaDeaApuHtMuxRr8UTuMwE0QSkNOswYeZnOuutYDnH2Zdpzj5cEFvP9um9YflUmp/bvixzh6thwviwxWSyLFpmp1wyvKiXxGt87m+8S3IfMYFwT2LJySxcMDU3r39sE+xS3Uxt3yNolfMbnOQU//Wf+4wsM1ICffT7Av7Y9KAoSY9lFuqZs7kXJCs1/eczpPYCDQ8CBHY/wyxigq+VoYrYSpAivHWDf+y1K0CQR5DmrbnxsLnXvQxRv+u/kwW7cXkLPJj8CLFdtczXXJhOk4qku03369kPVwDifCITbkGazI2Jg2f9AElkOYUQRKf78oWWyNjQyR7UtnNZ3rCidV4RA645U1mKqU7GrRS8H+ZyFuryk/8z3SiECvwH/rypfCp2kyHXWPr2uIVTHhapt8Hdb0E="
  local_dir: codedeploy
  bucket: ec2.csye6225-fall2017-jainyo.me.csye6225.com
  region: us-east-1
  skip_cleanup: true

- provider: codedeploy
  access_key_id: AKIAJJURQ7HUKCJBHXIA
  bucket: ec2.csye6225-fall2017-jainyo.me.csye6225.com
  key: WebApp1.zip
  bundle_type: zip
  application: WebApplication
  deployment_group: WebApplication
  region: us-east-1
  secret_access_key:
    secure: "pXk6T4/9Kf8GKZbx/umbgsUrY9ds+MQLo3xCbnVlxukO2DL5J7qWfX7LRndn6HkzWpSFJdo/TfAF+mAAW9jBRom4Bx7dvue9gaeNfxmy7ESpBzPIq9UTfExUFPkD8be3s7NwXTVXThxdWNFcn+ITS8lRQLIlmvpLXthbJ0jjAYE9Saw0MGK8EjcN2SXHa4K5a/YsUER5lRBkaCDM4aOkzCvl1e4gDmY55RkjidzgXkGM/8qAda9rVHD5Xs+OcBng/3UCaYW+LGI8WYw9XJvaDeaApuHtMuxRr8UTuMwE0QSkNOswYeZnOuutYDnH2Zdpzj5cEFvP9um9YflUmp/bvixzh6thwviwxWSyLFpmp1wyvKiXxGt87m+8S3IfMYFwT2LJySxcMDU3r39sE+xS3Uxt3yNolfMbnOQU//Wf+4wsM1ICffT7Av7Y9KAoSY9lFuqZs7kXJCs1/eczpPYCDQ8CBHY/wyxigq+VoYrYSpAivHWDf+y1K0CQR5DmrbnxsLnXvQxRv+u/kwW7cXkLPJj8CLFdtczXXJhOk4qku03369kPVwDifCITbkGazI2Jg2f9AElkOYUQRKf78oWWyNjQyR7UtnNZ3rCidV4RA645U1mKqU7GrRS8H+ZyFuryk/8z3SiECvwH/rypfCp2kyHXWPr2uIVTHhapt8Hdb0E="
  wait-until-deployed: true

notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu
