branches:
  only:
  - assignment3

language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew test --info 
  
notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu
