branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build

after_success:
  - mkdir codedeploy
  - zip -r WebApp1.zip build/libs/ROOT.war appspec.yml restartTomcat.sh infrastructure/aws/cloudwatch/awslogs.conf startCloudWatch.sh
  - ls -al
  - mv WebApp1.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al
  - cd ..
  - mkdir deploy_to_s3
  - cp appspec.yml deploy_to_s3/appspect.yml
  - cd deploy_to_s3
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd
  - gem update --system
  - cd deploy_to_s3
  - ls -al
  
deploy:
  - provider: s3
  access_key_id: $access_key_id
  secret_access_key: $access_key
  bucket: storageforgithubdeploy
  region: ap-northeast-2
  skip_cleanup: true

