branches:
  only:
  - assignment3

language: java
jdk:
  - oraclejdk8
services:
  - mysql
  
test:
  adapter: mysql2
  database: user_database
  username: travis
  encoding: utf8
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS user_database;'
env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew test --info 
  
notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu
