branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build

after_success:
  - mkdir codedeploy
  - zip -r WebApp1.zip build/libs/ROOT.war appspec.yml restartTomcat.sh infrastructure/aws/cloudwatch/awslogs.conf startCloudWatch.sh
  - ls -al
  - mv WebApp1.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd
  - gem update --system

deploy:
- provider: s3
  access_key_id: $access_key_id
  secret_access_key: $access_key
  bucket: storageforgithubdeploy
  region: ap-northeast-2
  skip_cleanup: true

- provider: codedeploy
  access_key_id: $access_key_id
  secret_access_key: $access_key
  bucket: storageforgithubdeploy
  key: codedeploy/WebApp1.zip
  bundle_type: zip
  application: CodeDeployGitHubDemo-App
  deployment_group: CodeDeployGitHubDemo-DepGrp
  region: ap-northeast-2
  wait-until-deployed: true

