branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

##test:
  ##adapter: mysql2
  #database: user_database
  #username: travis
  #encoding: utf8

#before_install:
 # - mysql -e 'CREATE DATABASE IF NOT EXISTS user_database;'
env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build
  #- ./gradlew test --info

after_success:
  - mkdir codedeploy
  - zip -r WebApp.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv WebApp.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd

deploy:
- provider: s3
  access_key_id: AKIAIXX72ODDFLYICJEA
  secret_access_key:
    secure: "hBfo7MwCNDWKADNtjsYWFmLQes1mD/YDBGJ/ah3KtjlbgyXwlHmU9fk4ZG61SA4iLmWfPhXJgOw8+tdF6+/BazGvizovChaIYAKYF/XS9ZJ4vo6zVA1GfF64vteJbwNI986gJeBFzU2RjzKjjKNtSY41kkijerSBGQL93K7GRwSl0RZPtxeQbq+/Boc/P+UAUOrmnuoL9KgrR9R3/He//9gEnzmgn21qcwCNYxsHKxC6enQtRb37S4cMkeXTYTJ9NHU/I3xLe8bz/UAaulMXb1mP04HUrKOmeX6ncU/PbhU+82izSwi7TKpfDMSnDZpRnUNJX6F2B+EUFvNkRC07JnVdh03nzjf1lgMomUzPMtrr7IdWUkG39Z3UJ80rd4x6YQarEgKL5PQnr4NYAn2tx1z69Mo+eG4FjxkBHiSPAJY39EU3ofbR7DwvkzaPM5eifZHxwzup5CEJLJaMxeBB3JF4LGd7Ad53WPWHnkoeqnEpg1pFZlpr9W6OI7E+MFF36V744gJgeXS4YO9Me5wf185iMiOA07lO+5cyPFw+R6AnYB8QmIZkh0E6PMimR+D1CpNCT8+b3kqEmfILdFBPs0DJNzKObiTCpfZySy2wHsHBI/8h90XUPh7TLytGs4lMNlqxTIzehx3Caoaqr1OWwkBfXNXa+rb9VXN+EjQqu4U="
  local_dir: codedeploy
  bucket: ec2.csye6225-fall2017-shettypr.me.csye6225.com
  region: us-east-1
  skip_cleanup: true

  #- provider: codedeploy
  #  access_key_id:
  #  bucket:
  #  key:
  #  bundle type: zip
  #application: WebApplication
   #deployement_group: WebApplication
- provider: codedeploy
  access_key_id: AKIAIXX72ODDFLYICJEA
  bucket: ec2.csye6225-fall2017-shettypr.me.csye6225.com
  key: WebApp.zip
  bundle_type: zip
  application: csye6225
  deployment_group: csye6225
  region: us-east-1
  secret_access_key:
    secure: "hBfo7MwCNDWKADNtjsYWFmLQes1mD/YDBGJ/ah3KtjlbgyXwlHmU9fk4ZG61SA4iLmWfPhXJgOw8+tdF6+/BazGvizovChaIYAKYF/XS9ZJ4vo6zVA1GfF64vteJbwNI986gJeBFzU2RjzKjjKNtSY41kkijerSBGQL93K7GRwSl0RZPtxeQbq+/Boc/P+UAUOrmnuoL9KgrR9R3/He//9gEnzmgn21qcwCNYxsHKxC6enQtRb37S4cMkeXTYTJ9NHU/I3xLe8bz/UAaulMXb1mP04HUrKOmeX6ncU/PbhU+82izSwi7TKpfDMSnDZpRnUNJX6F2B+EUFvNkRC07JnVdh03nzjf1lgMomUzPMtrr7IdWUkG39Z3UJ80rd4x6YQarEgKL5PQnr4NYAn2tx1z69Mo+eG4FjxkBHiSPAJY39EU3ofbR7DwvkzaPM5eifZHxwzup5CEJLJaMxeBB3JF4LGd7Ad53WPWHnkoeqnEpg1pFZlpr9W6OI7E+MFF36V744gJgeXS4YO9Me5wf185iMiOA07lO+5cyPFw+R6AnYB8QmIZkh0E6PMimR+D1CpNCT8+b3kqEmfILdFBPs0DJNzKObiTCpfZySy2wHsHBI/8h90XUPh7TLytGs4lMNlqxTIzehx3Caoaqr1OWwkBfXNXa+rb9VXN+EjQqu4U="
  wait-until-deployed: true


notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu