branches:
  only:
  - assignment9

language: java
jdk:
  - oraclejdk8
services:
  - mysql

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build

after_success:
  - mkdir codedeploy
  - zip -r WebApp1.zip build/libs/ROOT.war appspec.yml restartTomcat.sh infrastructure/aws/cloudwatch/awslogs.conf startCloudWatch.sh
  - ls -al
  - mv WebApp1.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd

deploy:
- provider: s3
  access_key_id: AKIAJJURQ7HUKCJBHXIA
  secret_access_key:
    secure: "ILCwDHVQtpxma902QYiyfbdCmBz1p3drjArwREMX/n9SDySfJB/b84cG5sm28LovZIYcHktjpkaTDNfqJF4e9skITbMdRRie58rUTwk5y0e0aic3TuTMCC96Cy1M6M7FT7HeMEIntWoNBc4CPZLgSlMzJQsK6XG/ejjwts2gRV/xIXdHfuZL/Vdk7RWvVOH3bliKxL122iO3wA+VQUBLXKrRVTBquRHcLVVpL3iwrW6qlIRpWU095RKWJ+yUb2gB4rmUR+Ma4VA3JOgRV72F8jO4+eMzHa0mIdCXfm1pnn5QVKXXyS9ICIjXmtGd6+QlokcIn0/whH/zDMWYrR1a0CSdLbEQ/LqQIfIBe45i85tRKlQxDSY4tcAnaMsoUdDEaGmqBqhYCsJfzdNqjgnA3FIyYet9+bglpi4K7gBmCDeTA/wLasxlnNZpedt9T97eQ4DwVn2vpvTdQghM/u/+prmmpZIKo9V4uG9+tjyq9iN4YT8Uv8fd7WMIjuRvOVbhXl/vbnD7EtHCQd8r1qmvhmA5nOs7xR3w8r1Ib2F7bhAVAUhl3QoS1YmjFDVs77v/Zu1IAhc8uxbjWoG2VbwPNUVQawBEnQMYN8RdmRLvFj5pkZBYSGaZUIAjnMMPgVVx4QNGc3iZIVvkXmFkbgwvYgeHZ1Cl7Hr39UdT3HOULEQ="
  local_dir: codedeploy
  bucket: ec2.csye6225-fall2017-jainyo.me.csye6225.com
  region: us-east-1
  skip_cleanup: true

- provider: codedeploy
  access_key_id: AKIAJJURQ7HUKCJBHXIA
  bucket: ec2.csye6225-fall2017-jainyo.me.csye6225.com
  key: WebApp1.zip
  bundle_type: zip
  application: WebApplication
  deployment_group: WebApplication
  region: us-east-1
  secret_access_key:
    secure: "ILCwDHVQtpxma902QYiyfbdCmBz1p3drjArwREMX/n9SDySfJB/b84cG5sm28LovZIYcHktjpkaTDNfqJF4e9skITbMdRRie58rUTwk5y0e0aic3TuTMCC96Cy1M6M7FT7HeMEIntWoNBc4CPZLgSlMzJQsK6XG/ejjwts2gRV/xIXdHfuZL/Vdk7RWvVOH3bliKxL122iO3wA+VQUBLXKrRVTBquRHcLVVpL3iwrW6qlIRpWU095RKWJ+yUb2gB4rmUR+Ma4VA3JOgRV72F8jO4+eMzHa0mIdCXfm1pnn5QVKXXyS9ICIjXmtGd6+QlokcIn0/whH/zDMWYrR1a0CSdLbEQ/LqQIfIBe45i85tRKlQxDSY4tcAnaMsoUdDEaGmqBqhYCsJfzdNqjgnA3FIyYet9+bglpi4K7gBmCDeTA/wLasxlnNZpedt9T97eQ4DwVn2vpvTdQghM/u/+prmmpZIKo9V4uG9+tjyq9iN4YT8Uv8fd7WMIjuRvOVbhXl/vbnD7EtHCQd8r1qmvhmA5nOs7xR3w8r1Ib2F7bhAVAUhl3QoS1YmjFDVs77v/Zu1IAhc8uxbjWoG2VbwPNUVQawBEnQMYN8RdmRLvFj5pkZBYSGaZUIAjnMMPgVVx4QNGc3iZIVvkXmFkbgwvYgeHZ1Cl7Hr39UdT3HOULEQ="
  wait-until-deployed: true

notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      #- magare.r@husky.neu.edu
      #- shetty.pr@husky.neu.edu
      #- gupta.rite@husky.neu.edu
