branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

##test:
  ##adapter: mysql2
  #database: user_database
  #username: travis
  #encoding: utf8

#before_install:
 # - mysql -e 'CREATE DATABASE IF NOT EXISTS user_database;'
env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build
  #- ./gradlew test --info

after_success:
  - mkdir codedeploy
  - zip -r WebApp.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv WebApp.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd


deploy:
- provider: s3
  access_key_id: AKIAJO6XPZC7EQMR6CQA
  secret_access_key:
    secure: "QxbNGA1Et8w2y5swsuArgTdQUcngI88+g/1zm0Ei76296HjwrjQPxQZTljs+sRjnwySBNIajCIZCZfKRQWwNVjBDUvvYZeeiqv7DIeD0LsNkNOrUV+ZeXDHBdKUfunoQLLcHclXgUHQ53uA++GTsYizk1pvsF7nad7LGxWGi2P65c5Zaa2nayJud11RT+4R2VHWzu9tLftwfEmIw/smUY3dvOpzPSkyd2Ujk118Uo5I5OkOr2hV9WO/UzRJh4W5+buEUhYZkxDSOyHwl0c77R9v0kedwtngoz4Ds/zfTzoDiokNvaXPJRo+/O9f7mvqLXna53ZagsvqTqV+BxqKYm3vuJXK9qCPC5xmgD9n5iiRPi0bUk5Dv8mnWD9imfozfhjYzxMzhOdm0iVkbH3i51xBWdGPzzcvnqNHTg2unp4wssTA3dVlstwHLcoAy2Qv9Ab8vCHeNvRm6vr5E6T8K1w4EKZAI3oa3rzjvm/1+FyJ80rIvQb2KN6bcWmQFPlFpxEjzSZiKR3S5eIbPA4TJ2ZsssRUvehTt5E+vKFveuUOG/v7yHesLx0/udpaIusOyMc40VgQBLGTzY6EOmx6YHc/MlVwDKklR9ulghG0Ml9mcyx2Xy3KdgnKGyQ3cpGrjmjsr5RDk/5BJ0cd9mTEyyphaP0szTbN3xo76t9ATqHU="
  local_dir: codedeploy
  bucket: ec2.csye6225-fall2017-magarer.me.csye6225.com
  region: us-east-1
  skip_cleanup: true

  #- provider: codedeploy
  #  access_key_id:
  #  bucket:
  #  key:
  #  bundle type: zip
  #application: WebApplication
   #deployement_group: WebApplication
- provider: codedeploy
  access_key_id: AKIAJO6XPZC7EQMR6CQA
  bucket: ec2.csye6225-fall2017-magarer.me.csye6225.com
  key: WebApp.zip
  bundle_type: zip
  application: WEB_APPLICATION
  deployment_group: WEB_APPLICATION
  region: us-east-1
  secret_access_key:
    secure: "QxbNGA1Et8w2y5swsuArgTdQUcngI88+g/1zm0Ei76296HjwrjQPxQZTljs+sRjnwySBNIajCIZCZfKRQWwNVjBDUvvYZeeiqv7DIeD0LsNkNOrUV+ZeXDHBdKUfunoQLLcHclXgUHQ53uA++GTsYizk1pvsF7nad7LGxWGi2P65c5Zaa2nayJud11RT+4R2VHWzu9tLftwfEmIw/smUY3dvOpzPSkyd2Ujk118Uo5I5OkOr2hV9WO/UzRJh4W5+buEUhYZkxDSOyHwl0c77R9v0kedwtngoz4Ds/zfTzoDiokNvaXPJRo+/O9f7mvqLXna53ZagsvqTqV+BxqKYm3vuJXK9qCPC5xmgD9n5iiRPi0bUk5Dv8mnWD9imfozfhjYzxMzhOdm0iVkbH3i51xBWdGPzzcvnqNHTg2unp4wssTA3dVlstwHLcoAy2Qv9Ab8vCHeNvRm6vr5E6T8K1w4EKZAI3oa3rzjvm/1+FyJ80rIvQb2KN6bcWmQFPlFpxEjzSZiKR3S5eIbPA4TJ2ZsssRUvehTt5E+vKFveuUOG/v7yHesLx0/udpaIusOyMc40VgQBLGTzY6EOmx6YHc/MlVwDKklR9ulghG0Ml9mcyx2Xy3KdgnKGyQ3cpGrjmjsr5RDk/5BJ0cd9mTEyyphaP0szTbN3xo76t9ATqHU="
  wait-until-deployed: true


notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu
