branches:
  only:
  - assignment3
env:
  - DB=mysql
  - test=unit
language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - gradle src/test/java/com/csye6225/demo/rest_assured/LoginUserTest
