branches:
  only:
  - master

language: java
jdk:
  - oraclejdk8
services:
  - mysql

##test:
  ##adapter: mysql2
  #database: user_database
  #username: travis
  #encoding: utf8

#before_install:
 # - mysql -e 'CREATE DATABASE IF NOT EXISTS user_database;'
env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - ./gradlew build
  #- ./gradlew test --info

after_success:
  - mkdir codedeploy
  - zip -r WebApp.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv WebApp.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - pwd
  - ls -al

before_deploy:
  - cd ..
  - ls -al
  - pwd


deploy:
- provider: s3
  access_key_id: AKIAJO6XPZC7EQMR6CQA
  secret_access_key:
    secure: "ZAxqlbbXTuN4EwEF2/CZSOU8pNGh27mzH3wwROVzoIvnrdGGE7b8wNKXS5fcgiJCmlA207nnSv0erjHXnvMooaatTeMz7MKd/w4eL1dVTCxnn/Oser0DSDB4J0tHyZctyIEIglib6+A7MZ7r4INqgFo/11yfxjV4l47Pl/BBrKIr9OUY+YY9yB9rgkS8qHRwkAuKDy2py4LeJ9fpNn4Re8BRmJtF29aRMf2b3iSjBEtgLqI+qs4F3khBb3j3WFnXBIrIm/BLIhKqJ5l/pxhEV/ex27l9IqDMiOj/t4S0qlhoP0hQslsOqJqr0qHyJLrP8EyGyi+pQ9hVRa2uvl7uhdtxBb7CMlzDuTS/cZNqfSsGQ+Uy/v66zZT9U+XBfDsS6zxg+fvvZMjSaF+pbSj6z4mjtDleNYxfkS7sYaB5ox8X7PfzbV6+YnAzJv3FjOjDoUNZdnW2qOwwOHxFMolf3NxZM4FkD1pfV5DbV5/yVheDJAxN1ZOxISByt5iz5X2uWrmPG0u/vhRVYm18rqwcR1q9hhMQHoiGoUJoZjl+AdsULMoaDrSkU3hF4Qoj+i+jBjIwtgywmKccHKAG8NvcHbAp//Ykmpkd5jtD+/9Xk3out9Xz04spTBU4SETuLiavRFVzcB0PQdJF3AeF8MaxmjbBcTLzE7BSg92jW+azJY4="
  local_dir: codedeploy
  bucket: ec2.csye6225-fall2017-magarer.me.csye6225.com
  region: us-east-1
  skip_cleanup: true

  #- provider: codedeploy
  #  access_key_id:
  #  bucket:
  #  key:
  #  bundle type: zip
  #application: WebApplication
   #deployement_group: WebApplication
- provider: codedeploy
  access_key_id: AKIAJO6XPZC7EQMR6CQA
  bucket: ec2.csye6225-fall2017-magarer.me.csye6225.com
  key: WebApp.zip
  bundle_type: zip
  application: WEB_APPLICATION
  deployment_group: WEB_APPLICATION
  region: us-east-1
  secret_access_key:
    secure: "ZAxqlbbXTuN4EwEF2/CZSOU8pNGh27mzH3wwROVzoIvnrdGGE7b8wNKXS5fcgiJCmlA207nnSv0erjHXnvMooaatTeMz7MKd/w4eL1dVTCxnn/Oser0DSDB4J0tHyZctyIEIglib6+A7MZ7r4INqgFo/11yfxjV4l47Pl/BBrKIr9OUY+YY9yB9rgkS8qHRwkAuKDy2py4LeJ9fpNn4Re8BRmJtF29aRMf2b3iSjBEtgLqI+qs4F3khBb3j3WFnXBIrIm/BLIhKqJ5l/pxhEV/ex27l9IqDMiOj/t4S0qlhoP0hQslsOqJqr0qHyJLrP8EyGyi+pQ9hVRa2uvl7uhdtxBb7CMlzDuTS/cZNqfSsGQ+Uy/v66zZT9U+XBfDsS6zxg+fvvZMjSaF+pbSj6z4mjtDleNYxfkS7sYaB5ox8X7PfzbV6+YnAzJv3FjOjDoUNZdnW2qOwwOHxFMolf3NxZM4FkD1pfV5DbV5/yVheDJAxN1ZOxISByt5iz5X2uWrmPG0u/vhRVYm18rqwcR1q9hhMQHoiGoUJoZjl+AdsULMoaDrSkU3hF4Qoj+i+jBjIwtgywmKccHKAG8NvcHbAp//Ykmpkd5jtD+/9Xk3out9Xz04spTBU4SETuLiavRFVzcB0PQdJF3AeF8MaxmjbBcTLzE7BSg92jW+azJY4="
  wait-until-deployed: true


notifications:
  email:
    recipients:
      - jain.yo@husky.neu.edu
      - magare.r@husky.neu.edu
      - shetty.pr@husky.neu.edu
      - gupta.rite@husky.neu.edu
