AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VpcId:
    Description: Vpc id of the AMI
    Type: "String"
  WebServerSecurityGroup:
    Description: Security Group name
    Type: "String"
  DBSecurityGroup:
    Description: Security Group name
    Type: "String"
  DBName:
    Description: Name of the RDS database
    Type: "String"
  DBAllocatedStorage:
    Description: DBAllocatedStorage for RDS instance
    Type: "String"
  DBInstanceClass:
    Description: Instance class type for the RDS database
    Type: "String"
  DBUser:
    Description: database user name for RDS instance
    Type: "String"
  DBPassword:
    Description: database password of the RDS database
    Type: "String"
  DatabaseType:
    Description: "Type of database: MySQL, Sql"
    Type: "String"
  DatabaseVersion:
    Description: Version of database engine
    Type: "String"
  DBStorageType:
    Description: "Type of Storage gp2 or io1"
    Type: "String"
  InstanceIdentifier:
    Description: Name of instance identifier
    Type: "String"
  SubnetId1:
    Description: Subnet Id for us-east-1c
    Type: "String"
  SubnetId2:
    Description: Subnet Id for us-east-1b
    Type: "String"
  BucketName:
    Description: Name of the S3 bucket
    Type: "String"
  DynamodbTableName:
    Description: Name of the Dynamodb
    Type: "String"
  ReadCU:
    Description: Read capacity units for Dynamodb
    Type: "String"
  WriteCU:
    Description: Write capacity units for Dynamodb
    Type: "String"
  ColumnName:
    Description: PrimaryKey Name for DB
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: "only alphanumberic characters"
  IdDataType:
    Description: Id PrimaryKey Data Type
    Type: String
    Default: S
    AllowedPattern: '[S|N]'
    MinLength: '1'
    MaxLength: '1'
    ConstraintDescription: "must be either S or N"
  WebserverPort:
    Description: TCP server port 80 Instance
    Type: "String"
  HttpPort:
    Description: Http port for EC2 Instance
    Type: "String"
  HttpsPort:
    Description: Https port for EC2 Instance
    Type: "String"
  DBIngressPort:
    Description: MySQL db Ingress port for RDS Instance
    Type: "String"


Resources:
# VPC Security Group for EC2 instance
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Ref WebServerSecurityGroup
      GroupDescription: Base Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref WebserverPort #'80'
          ToPort: !Ref WebserverPort #'80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref HttpPort #'22'
          ToPort: !Ref HttpPort #'22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref HttpsPort #'443'
          ToPort: !Ref HttpsPort #'443'
          CidrIp: 0.0.0.0/0
# VPC Security Group for RDS instance
  RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Ref DBSecurityGroup
      VpcId: !Ref VpcId
      GroupDescription: Base Security Group
# Ingress rule for RDS instance
  RDSIngressSecurity:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      FromPort: !Ref DBIngressPort #'3306'
      ToPort: !Ref DBIngressPort #'3306'
      SourceSecurityGroupId: !Ref EC2SecurityGroup
      GroupId: !Ref RDSSecurityGroup
# Subnet group for RDS instance
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "New subnet for RDS instance"
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2

# RDS instance
  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref DatabaseType
      EngineVersion: !Ref DatabaseVersion
      StorageType: !Ref DBStorageType
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceIdentifier: !Ref InstanceIdentifier
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      MultiAZ: false
      VPCSecurityGroups:
      - Ref: RDSSecurityGroup
      Tags:
        -
          Key: "Name"
          Value: "RDS MySQL Database"

# S3 bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private

# DynamoDB Table
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: !Ref ColumnName
          AttributeType: !Ref IdDataType
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCU
        WriteCapacityUnits: !Ref WriteCU
      TableName: !Ref DynamodbTableName

Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the Amazon S3 bucket
