AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to create a RDS instance

Parameters:
  DBName:
    Description: Name of the RDS database
    Type: "String"
  DBAllocatedStorage:
    Description: DBAllocatedStorage for RDS instance
    Type: "String"
  DBInstanceClass:
    Description: Instance class type for the RDS database
    Type: "String"
  DBUser:
    Description: database user name for RDS instance
    Type: "String"
  DBPassword:
    Description: database password of the RDS database
    Type: "String"

Resources:
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "New subnet for RDS instance"
      SubnetIds:
        - "subnet-8dd7f9a1"
        - "subnet-b833dcf3"
  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName:
        Ref: "DBName"
      AllocatedStorage:
        Ref: "DBAllocatedStorage"
      DBInstanceClass:
        Ref: "DBInstanceClass"
      Engine: "MySQL"
      EngineVersion: "5.6.35"
      StorageType: "gp2"
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceIdentifier: "csye6255-fall2017"
      PubliclyAccessible: false
      #DBSecurityGroups: ""
      MasterUsername:
        Ref: "DBUser"
      MasterUserPassword:
        Ref: "DBPassword"
      Tags:
        -
          Key: "Name"
          Value: "My SQL Database"
      MultiAZ: false
    #DeletionPolicy: "Snapshot"
